[tool.poetry]
name = "aoc2025"
version = "0.1.0"
description = ""
authors = ["Sam Tarver <sam.tarver@ourfuturehealth.org.uk>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
